version: '3.8'

services:
  db:
    image: postgres:16-alpine 
    container_name: restaurante_postgres
    restart: always
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: admin_restaurante
      POSTGRES_PASSWORD: password_seguro_123
      POSTGRES_DB: restaurante_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data 
